import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import "@radix-ui/themes/styles.css"
import { Theme } from "@radix-ui/themes"
import AuthProvider from "@/context/AuthProvider"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Dexx - AI Study Partner",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <AuthProvider>
          <Theme
            accentColor="crimson"
            grayColor="sand"
            radius="large"
            scaling="95%"
          >
            {children}
            <Toaster />
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
